### ISSUE TITLE
Need a development branch

### ISSUE THREAD

**Issue by MrChadMWood** [sgriffin53/openingexplorer_app#2]
Id like to submit a PR but the only branch is main. Can there be a branch for work in progress?

**Comment by sgriffin53** [comment]
Hi, thanks for forking my project and improving it. I've just made a "dev" branch that you can push to. Thanks.

**Comment by MrChadMWood** [comment]
Great. Yes, I just went for a refactor but it is not working at the moment. Don’t want to merge my broken code into main now.

There were some parts I had a hard time conceptualizing, around all the dynamically generated JavaScript. It’s a big file with a lot going on.

If you’re interested, I think we can start by organizing and documenting the code. Then I’d be curious about how we can improve things / add new features.

As it stands right now, adding new features is going to add a lot of technical debt.
